//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKP.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cn_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cn_zh() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DKP.Web.Resources.cn-zh", typeof(cn_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 基础资料 的本地化字符串。
        /// </summary>
        internal static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 融资方管理 的本地化字符串。
        /// </summary>
        internal static string CompanyManager {
            get {
                return ResourceManager.GetString("CompanyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户管理 的本地化字符串。
        /// </summary>
        internal static string CustmerManagement {
            get {
                return ResourceManager.GetString("CustmerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计分析 的本地化字符串。
        /// </summary>
        internal static string DataAnalyt {
            get {
                return ResourceManager.GetString("DataAnalyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 债权转让管理 的本地化字符串。
        /// </summary>
        internal static string DebtAssignment {
            get {
                return ResourceManager.GetString("DebtAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Edit1 {
            get {
                return ResourceManager.GetString("Edit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 财务管理 的本地化字符串。
        /// </summary>
        internal static string FinanceManagement {
            get {
                return ResourceManager.GetString("FinanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租约管理 的本地化字符串。
        /// </summary>
        internal static string LeaseManagement {
            get {
                return ResourceManager.GetString("LeaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 融资管理 的本地化字符串。
        /// </summary>
        internal static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的工作 的本地化字符串。
        /// </summary>
        internal static string MyWork {
            get {
                return ResourceManager.GetString("MyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还款管理 的本地化字符串。
        /// </summary>
        internal static string Papayment {
            get {
                return ResourceManager.GetString("Papayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租赁物管理 的本地化字符串。
        /// </summary>
        internal static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品管理 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再融资管理 的本地化字符串。
        /// </summary>
        internal static string RefinanceManagement {
            get {
                return ResourceManager.GetString("RefinanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表中心 的本地化字符串。
        /// </summary>
        internal static string ReportCenter {
            get {
                return ResourceManager.GetString("ReportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全管理 的本地化字符串。
        /// </summary>
        internal static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助工具 的本地化字符串。
        /// </summary>
        internal static string Toolkit {
            get {
                return ResourceManager.GetString("Toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员管理 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站管理 的本地化字符串。
        /// </summary>
        internal static string Websit {
            get {
                return ResourceManager.GetString("Websit", resourceCulture);
            }
        }
    }
}
