//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKP.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DKP.Web.Resources.en-us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BasicData 的本地化字符串。
        /// </summary>
        internal static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custmer 的本地化字符串。
        /// </summary>
        internal static string CustmerManagement {
            get {
                return ResourceManager.GetString("CustmerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit1 {
            get {
                return ResourceManager.GetString("Edit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finance 的本地化字符串。
        /// </summary>
        internal static string FinanceManagement {
            get {
                return ResourceManager.GetString("FinanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease 的本地化字符串。
        /// </summary>
        internal static string LeaseManagement {
            get {
                return ResourceManager.GetString("LeaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Work 的本地化字符串。
        /// </summary>
        internal static string MyWork {
            get {
                return ResourceManager.GetString("MyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        internal static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refinance 的本地化字符串。
        /// </summary>
        internal static string RefinanceManagement {
            get {
                return ResourceManager.GetString("RefinanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string ReportCenter {
            get {
                return ResourceManager.GetString("ReportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolkit 的本地化字符串。
        /// </summary>
        internal static string Toolkit {
            get {
                return ResourceManager.GetString("Toolkit", resourceCulture);
            }
        }
    }
}
