//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKP.Data
{
    using System;
    using System.Collections.Generic;
    using DKP.Core.Data;
    using DKP.Core.Extensions;
    
    /// <summary>
    /// 附件
    /// </summary>
    public partial class Attachment : BaseEntity
    {
        /// <summary>
        /// 附件名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 上传时间
        /// </summary>
        public System.DateTime? UploadDate { get; set; }
        /// <summary>
        /// 文件类型
        /// </summary>
        public string FileType { get; set; }
        /// <summary>
        /// 文件大小
        /// </summary>
        public int? FileSize { get; set; }
        /// <summary>
        /// 文件保存名
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FilePath { get; set; }
        /// <summary>
        /// 上传人
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 外键分类
        /// </summary>
        public int? Category { get; set; }
        /// <summary>
        /// 外键
        /// </summary>
        public int? ForeignKey { get; set; }
    
        public virtual User User { get; set; }
    }
}
