//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKP.Data
{
    using System;
    using System.Collections.Generic;
    using DKP.Core.Data;
    using DKP.Core.Extensions;
    
    /// <summary>
    /// 数据字典
    /// </summary>
    public partial class Dictionary : BaseEntity
    {
        /// <summary>
        /// 编码
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 所属组
        /// </summary>
        public int? DictionaryGroupId { get; set; }
    
        public virtual DictionaryGroup DictionaryGroup { get; set; }
    }
}
