//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKP.Data
{
    using System;
    using System.Collections.Generic;
    using DKP.Core.Data;
    using DKP.Core.Extensions;
    
    /// <summary>
    /// ScheduleTask
    /// </summary>
    public partial class ScheduleTask : BaseEntity
    {
        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int Seconds { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool StopOnError { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? LastStartUtc { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? LastEndUtc { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? LastSuccessUtc { get; set; }
    }
}
