//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace DKP.Data
{
    using System;
    using System.Collections.Generic;
    using DKP.Core.Data;
    using DKP.Core.Extensions;
    
    /// <summary>
    /// User
    /// </summary>
    public partial class User : BaseEntity
    {
        public User()
        {
            this.Attachments = new List<Attachment>();
            this.Roles = new List<Role>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Salt { get; set; }
        /// <summary>
        /// 中文名
        /// </summary>
        //public string RealName { get; set; }
        /// <summary>
        /// 手机号码
        /// </summary>
        public string Telephone { get; set; }
        /// <summary>
        /// 电子邮箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool IsLock { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public System.DateTime AddTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool IsSystem { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? DeptId { get; set; }
        /// <summary>
        /// 工号
        /// </summary>
        public string Number { get; set; }
        /// <summary>
        /// 籍贯
        /// </summary>
        public string NativePlace { get; set; }
        /// <summary>
        /// 名族
        /// </summary>
        public string FamilyName { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public string Sex { get; set; }
        /// <summary>
        /// 婚姻
        /// </summary>
        public string Marriage { get; set; }
        /// <summary>
        /// 文化程度
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 职位
        /// </summary>
        public string Position { get; set; }
        /// <summary>
        /// 传真
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// 入职日期
        /// </summary>
        public System.DateTime? EntryDate { get; set; }
        /// <summary>
        /// 离职日期
        /// </summary>
        public System.DateTime? LeaveDate { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 最后登陆时间
        /// </summary>
        public System.DateTime? LastLoginTime { get; set; }
        /// <summary>
        /// 英文名
        /// </summary>
        public string NameEN { get; set; }
        /// <summary>
        /// 身份证号码
        /// </summary>
        public string IDNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MemberType { get; set; }

        public string RealName { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string Avatar { get; set; }
        /// <summary>
        /// DKP上限
        /// </summary>
        public int? MaxDkp { get; set; }
        /// <summary>
        /// 特殊DKP
        /// </summary>
        public int? SpecialDkp { get; set; }

        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
